language: bash

services:
  - docker

script:
  - make
  - docker run --rm -it saxon:he xslt || true
  - docker run --rm -it saxon:he xquery || true
  - docker run --rm -it saxon:he-graal xslt || true
