language: bash

services:
  - docker

script:
  - make
  - docker run --rm -it saxon:default xslt || true
  - docker run --rm -it saxon:default xquery || true
  - docker run --rm -it saxon:graal xslt || true
