#!/bin/bash

if [ $SOURCE_BRANCH = "master" ]; then
  VERSION="dev"
else
  VERSION="$SOURCE_BRANCH"
fi

docker tag $DOCKER_REPO:$VERSION-base saxon:base

docker build -t $DOCKER_REPO:$VERSION-graal -f Dockerfile-graal .
docker push $DOCKER_REPO:$VERSION-graal

docker build -t $DOCKER_REPO:$VERSION-he -f Dockerfile-he .
docker push $DOCKER_REPO:$VERSION-he

docker tag $DOCKER_REPO:$VERSION-he $DOCKER_REPO:$VERSION
docker push $DOCKER_REPO:$VERSION

if [ $SOURCE_BRANCH != "master" ]; then
  docker tag $DOCKER_REPO:$VERSION-base $DOCKER_REPO:latest-base
  docker push $DOCKER_REPO:latest-base

  docker tag $DOCKER_REPO:$VERSION-base $DOCKER_REPO:base
  docker push $DOCKER_REPO:base

  docker tag $DOCKER_REPO:$VERSION-graal $DOCKER_REPO:latest-graal
  docker push $DOCKER_REPO:latest-graal

  docker tag $DOCKER_REPO:$VERSION-graal $DOCKER_REPO:graal
  docker push $DOCKER_REPO:graal

  docker tag $DOCKER_REPO:$VERSION-he $DOCKER_REPO:latest-he
  docker push $DOCKER_REPO:latest-he

  docker tag $DOCKER_REPO:$VERSION-he $DOCKER_REPO:latest
  docker push $DOCKER_REPO:latest
fi
